#!/bin/bash


# url file to scan 
#output file
#nuclei template
#sevirity
#occur

# test if there is already scan done before in this repo 
# to create a inore file  for this repos 


echo "step prepare template"
rm -rf ./ncl_temp 2&> /dev/null
cp -r $3 ./ncl_temp
cd  ./ncl_temp

if [[ -f ../.templates ]]; then
	for i in $(cat ../.templates);do
		find ./ -iname "$i" -exec rm -rf {} \;
	done
fi

cd -


# create  split for  scan file if  doesn t exist
if [[ ! $(find ./ -iname "host_*") ]]; then
	split -l 500 $1  host_
fi



echo "step 2 : scan"
#lanch the scan 
for file in $(ls host_* );do
	nuclei -l $file  -t ./ncl_temp   -stats -timeout 5  -severity $4  -c $5| anew $2 |notify -silent
	rm -rf $file
done
x 

echo "step3 : update .template file"

#get the templates that is used 
cd ./ncl_temp && find ./ -iname "*.yaml"  |grep -r  "$4" |cut -d ":" -f 1 | rev | cut -d'/' -f1 | rev   >> ../.templates && cd -
cat .templates |sort -uo .templates
rm -rf ./ncl_temp 





